- name: Check PostgreSQL Trigger
  hosts: all
  sources:
  - sources:
      - name: tick-check
        plugin: eda.plugins.event_source.tick
        configuration:
          interval: 60  # Check every 60 seconds
          payload:
            db_host: "{{ db_host }}"
            db_name: "{{ db_name }}"
            db_user: "{{ db_user }}"
            db_password: "{{ db_password }}"

    rules:
      - name: check for trigger queue.new_message_notify()
        action:
          run_job_template:
            name: check-postgres-trigger
            organization: "Default"
          