- name: Monitor PostgreSQL Role
  hosts: localhost
  sources:
    - ansible.eda.pg_listener:
        dsn: "hostaddr={{ db_hostaddr }} port=5432 dbname={{ db_name }} user={{ db_user }} password={{ db_password }}"
        channels:
          - text

  rules:
    - name: Check PostgreSQL role
      condition: event.data is defined
      action:
        run_playbook:
          name: playbooks/check_postgres_role.yml