- name: Monitor PostgreSQL Role
  hosts: localhost
  sources:
    type: tick
    tick_interval: 45

  rules:
    - name: Check PostgreSQL role
      condition: event.payload is defined
      action:
        run_job_template:
          name: Check Postgres

