- name: Monitor PostgreSQL Role
  hosts: all
  sources:
     - ansible.eda.tick:
        delay: 10

  rules:
    - name: Scale up
      action:
        run_job_template:
          name: "Check Postgres Trigger - Site 1 ..05"
          organization: "Default"
