- name: Monitor PostgreSQL Role
  hosts: localhost
  sources:
    - ansible.eda.pg_listener:
        postgres_params:
          host: "{{ db_host }}"
          port: 5432
          dbname: "{{ db_name }}"
        channels:
          - text

  rules:
    - name: Check PostgreSQL role
      condition: event.payload is defined
      action:
        run_job_template:
          name: Check Postgres