- name: Monitor PostgreSQL Role
  hosts: localhost
  sources:
    - ansible.eda.periodic:
        seconds: 60

  rules:
    - name: Check PostgreSQL role
      condition: event.payload is defined
      action:
        run_playbook:
          name: playbooks/check_postgres_role.yml
          extra_vars:
            db_host: "your.db.hostname.here"

