- name: Monitor PostgreSQL Role
  hosts: all
  sources:
    - ansible.eda.pg_listener:
        dsn: "host={{ db_host }} port=5432 dbname={{ db_name }} user={{ db_user }} password={{ db_password }}"
        channels: 
          - text

  rules:
    - name: Scale up
      condition: event.meta.pg_role contains "primary"
      action:
        run_job_template:
          name: "Scale up AAP Site 1 CR"
          organization: "Default"

    - name: Scale down
      condition: event.meta.pg_role contains "standby"
      action:
        run_job_template:
          name: "Scale down AAP Site 1 CR"
          organization: "Default"