- name: Monitor PostgreSQL Role
  hosts: all
  sources:
    - ansible.eda.file_watch:
        path: "/tmp/pg_role"

  rules:
    - name: Scale up
      condition: event.payload.pg_role contains "primary"
      action:
        run_job_template:
          name: "Scale up AAP CR"
          organization: "Default"

    - name: Scale down
      condition: event.data.pg_role contains "standby"
      action:
        run_job_template:
          name: "Scale down AAP CR"
          organization: "Default"