- name: Monitor PostgreSQL Role
  hosts: all
  sources:
     - ansible.eda.tick:
        delay: 5

  rules:
    - name: Scale up
      action:
        run_job_template:
          name: "Scale up AAP Site 1 CR"
          organization: "Default"
