- name: Monitor PostgreSQL Role
  hosts: localhost
  sources:
    - ansible.eda.tick:
        delay: 30

  rules:
    - name: Check PostgreSQL role
      condition: event.payload is defined
      action:
        run_job_template:
          name: Check Postgres

