- name: Monitor PostgreSQL Role
  hosts: all
  sources:
    - ansible.eda.pg_listener:
        dsn: "host=localhost port=5432 dbname=mydb"
        channels:
          - my_events
          - my_alerts

  rules:
    - name: Scale up
      action:
        run_job_template:
          name: "Scale up AAP Site 1 CR"
          organization: "Default"
