---
- name: Monitor PostgreSQL Role
  hosts: localhost
  sources:
    - ansible.eda.periodic:
        seconds: 60  # check every 60 seconds

  rules:
    - name: Check PostgreSQL role
      condition: event.payload is defined
      action:
        run_playbook:
          name: check_postgres_role.yml
          extra_vars:
            db_host: "your.db.hostname.here"

