- name: Monitor PostgreSQL Role
  hosts: localhost
  sources:
    - ansible.eda.pg_listener:
        postgres_params:
          hostaddr: "{{ db_host_ip }}"
          port: "{{ db_port }}"
          dbname: "{{ db_name }}"
          user: "{{ db_user }}"
          password: "{{ db_password }}"
        channels:
          - text

  rules:
    - name: Check PostgreSQL role
      condition: event.payload is defined
      action:
        run_job_template:
          name: Check Postgres