- name: Monitor PostgreSQL Role
  hosts: all
  sources:
    - ansible.eda.webhook:
        port: 5001

  rules:
    - name: Check Postgres Trigger
      action:
        run_job_template:
          name: "Check Postgres Trigger - Site 1 ..05"
          organization: "Default"
