---
- name: Process Alertmanager events to scale KubeVirt VM sockets
  hosts: all 

  sources:
    - ansible.eda.tick:
        delay: 5

  rules:
    - name: Print Information of Tick
      condition: event.i is defined
      action:
        debug:
          var: event
