- name: Monitor PostgreSQL Role
  hosts: all
  sources:
    - ansible.eda.tick:
        delay: 5

  rules:
    - name: Scale up
      condition: event.postgres_db_role == primary
      action:
        run_job_template:
          name: "Scale up AAP Site 1 CR"
          organization: "Default"

    - name: Scale down
      condition: event.postgres_db_role != primary
      action:
        run_job_template:
          name: "Scale down AAP Site 1 CR"
          organization: "Default"