---
- name: PG Trigger Check
  hosts: all 

  sources:
    - ansible.eda.tick:
        delay: 5

  rules:
    - name: Check PG Trigger
      condition: event.i is defined
      action:
        run_job_template:
          name: "Check Postgres Trigger - Site 1 ..05"
          organization: "Default"