---
- name: Check PostgreSQL Role
  hosts: all
  become: true
  become_method: sudo
  become_user: postgres
  gather_facts: false
  tasks:
    - name: Check if PostgreSQL is reachable
      command: |
        psql -U postgres -h {{ db_host }} -c "SELECT pg_is_in_recovery();"
      register: pg_status
      ignore_errors: true

    - name: Set fact based on status
      set_fact:
        pg_role: >-
          {% if pg_status.rc != 0 %}
            offline
          {% elif '"t"' in pg_status.stdout %}
            standby
          {% else %}
            primary
          {% endif %}

    - name: Use pg_notify to alert EDA of any changes. 
      command: | 
        psql -h "{{ db_host }}" -U postgres -d "{{ db_name }}" -c "NOTIFY text, '{\"postgres_db_role\":\"{{ pg_role | trim }}\"}'"
      ignore_errors: true