---
- name: Check PostgreSQL Role
  hosts: all
  become: true
  become_method: sudo
  become_user: postgres
  gather_facts: false
  tasks:
    - name: Check if PostgreSQL is reachable
      command: |
        psql -U postgres -h {{ db_host }} -c "SELECT pg_is_in_recovery();"
      register: pg_status
      ignore_errors: true

    - name: Set fact based on status
      set_fact:
        pg_role: >-
          {% if pg_status.rc != 0 %}
            offline
          {% elif '"t"' in pg_status.stdout %}
            standby
          {% else %}
            primary
          {% endif %}

    - name: Print PostgreSQL role
      debug:
        msg: "PostgreSQL is {{ pg_role }}"
    
    - name: Template the postgres file to the host and populate it with its role. 
      ansible.builtin.template:
        src: ../files/pg_role.j2
        dest: /tmp/pg_role
        owner: postgres
        group: postgres
        mode: '0644'