- name: Bring up AAP Site 1.
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Log in (obtain access token)
      redhat.openshift.openshift_auth:
        username: "{{ openshift_admin_user }}"
        password: "{{ openshift_admin_password }}"
        host: "{{ openshift_api_url }}"
        validate_certs: false
      register: openshift_auth_results

    - name: Scale AAP CR replicas according to role. 
      redhat.openshift.k8s:
        state: present
        api_version: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        name: controller-edb-01
        namespace: aap-24
        merge_type: strategic
        definition:
          spec:
            replicas: 0