- name: Bring up AAP Site 1.
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Sleep for 5 seconds
      ansible.builtin.pause:
        seconds: 1000
        
    - name: Check Kubernetes API access with service account token
      uri:
        url: https://kubernetes.aap-25.svc/version
        method: GET
        headers:
          Authorization: "Bearer {{ lookup('file', '/var/run/secrets/kubernetes.io/serviceaccount/token') }}"
        validate_certs: no
      register: api_check

    - debug:
        var: api_check

    - name: Scale AAP CR replicas according to role. 
      redhat.openshift.k8s:
        state: present
        api_version: automationcontroller.ansible.com/v1beta1
        kind: AutomationController
        name: controller-edb-01
        namespace: aap-24
        merge_type: strategic-merge 
        definition:
          spec:
            replicas: 0