- name: Bring down AAP Site 2. 
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Log in (obtain access token)
      redhat.openshift.openshift_auth:
        username: "{{ openshift_admin_user }}"
        password: "{{ openshift_admin_password }}"
        host: "{{ openshift_api_url }}"
        validate_certs: false
      register: openshift_auth_results

    - name: Scale AAP CR replicas according to role. 
      redhat.openshift.k8s:
        state: present
        src: ../files/aap-cr-down-site2.yml
        api_key: "{{ openshift_auth_results.openshift_auth.api_key }}"
        validate_certs: false